<html>
<head>
</head>
<body>
<script>
function jsonFlickrApi(rsp) {
 if (rsp.stat != "ok"){
  // If this executes, something broke!
  return;
 }
 
 //variable "s" is going to contain 
 //all the markup that is generated by the loop below
 var s = "";
 
 //this loop runs through every item and creates HTML 
 for (var i=0; i < rsp.photos.photo.length; i++) {
  photo = rsp.photos.photo[ i ];
  
  //notice that "t.jpg" is where you change the
  //size of the image
  t_url = "http://farm" + photo.farm + 
  ".static.flickr.com/" + photo.server + "/" + 
  photo.id + "_" + photo.secret + "_" + "t.jpg";
    
  p_url = "http://www.flickr.com/photos/" + 
  photo.owner + "/" + photo.id;
  
  s +=  '<div id="flickr_badge_image' + i + '" class="flickr_badge_image"><a href="' + p_url + '">' + '<img alt="'+ 
  photo.title + '"src="' + t_url + '"/>' + '</a></div>';
 }
 
 document.writeln(s); 
 //this tells the JavaScript to write 
 //everything in variable "s" onto the page
}
</script>

<script type="text/javascript" language="javascript" src="http://api.flickr.com/services/rest/?format=json&amp;method=flickr.photos.search&amp;user_id=38639158@N06&amp;sort=date-taken-desc&amp;api_key=7a4fa02aaaae7136da8596c91aacc5da"></script>
</body>
</html>
<!--

<div id="flickr-widget">
	<script src="http://www.flickr.com/badge_code_v2.gne?count=14&display=latest&size=s&layout=x&source=user&user=38639158@N06" type="text/javascript">
	<div id="flickr_badge_image1" class="flickr_badge_image">
		<a href="http://www.flickr.com/photos/fredbradley/8515636746/" target="_blank">
			<img title="IMG_0260" alt="A photo on Flickr" src="http://farm9.staticflickr.com/8366/8515636746_9c16b19a18_s.jpg">
		</a>
	</div>
</div> -->